'use client';

import { useState } from 'react';

const GOOGLE_FORM_ACTION = 'https://docs.google.com/forms/d/e/1FAIpQLSczUxo92cAaKfisq9NFqUWd9U0pbQGjatPWyzAEL-0C4arkyg/formResponse';
const ENTRY = {
  name:'entry.1005487632', kana:'entry.1851232665', email:'entry.1910842350', phone:'entry.1865738863',
  requestType:'entry.1565507572', landStatus:'entry.57448523', buildTiming:'entry.831853067', message:'entry.140735802',
};

const Icon = ({type}:{type:string}) => (
  <svg className="icon" viewBox="0 0 64 64" fill="none" stroke="currentColor" strokeWidth="2">
    {type==='house' && <><path d="M10 31L32 13l22 18"/><path d="M16 29v24h32V29"/><path d="M26 53V38h12v15"/></>}
    {type==='sun' && <><circle cx="32" cy="32" r="12"/><path d="M32 5v10M32 49v10M5 32h10M49 32h10M13 13l7 7M44 44l7 7M51 13l-7 7M20 44l-7 7"/></>}
    {type==='leaf' && <><path d="M47 12C25 13 13 25 14 47c22 1 34-11 33-35z"/><path d="M16 46c9-14 18-22 31-34"/></>}
    {type==='heart' && <><path d="M32 53S9 39 7 23c-1-10 11-16 20-6l5 6 5-6c9-10 21-4 20 6-2 16-25 30-25 30z"/></>}
    {type==='plan' && <><path d="M12 12h40v40H12z"/><path d="M12 30h18V12M30 52V34h22M40 24h12"/></>}
    {type==='thermo' && <><path d="M28 38V13a8 8 0 0116 0v25a14 14 0 11-16 0z"/><path d="M36 20v24"/></>}
  </svg>
);

export default function Home(){
  const [form,setForm]=useState({name:'',kana:'',email:'',phone:'',requestType:[] as string[],landStatus:'',buildTiming:'',message:''});
  const [status,setStatus]=useState<'idle'|'sending'|'success'|'error'>('idle');
  const requestOptions=['資料請求','モデルハウス見学','資金相談','プラン相談','その他'];
  const landOptions=['すでに土地がある','土地探しから','建て替え','未定'];
  const timingOptions=['3ヶ月以内','半年以内','1年以内','1〜2年以内','まだ未定'];
  const update=(e:React.ChangeEvent<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>)=>setForm({...form,[e.target.name]:e.target.value});
  const toggle=(v:string)=>setForm({...form,requestType:form.requestType.includes(v)?form.requestType.filter(x=>x!==v):[...form.requestType,v]});
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setStatus('sending');try{const d=new FormData();d.append(ENTRY.name,form.name);d.append(ENTRY.kana,form.kana);d.append(ENTRY.email,form.email);d.append(ENTRY.phone,form.phone);form.requestType.forEach(v=>d.append(ENTRY.requestType,v));d.append(ENTRY.landStatus,form.landStatus);d.append(ENTRY.buildTiming,form.buildTiming);d.append(ENTRY.message,form.message);await fetch(GOOGLE_FORM_ACTION,{method:'POST',mode:'no-cors',body:d});setStatus('success');setForm({name:'',kana:'',email:'',phone:'',requestType:[],landStatus:'',buildTiming:'',message:''});}catch{setStatus('error')}};

  const specs=[
    ['01','構造','強さと耐久性を追求した安心の構造計画。'],['02','基礎','不同沈下に強いベタ基礎工法。'],['03','断熱','高断熱で一年中快適な室内環境を実現。'],['04','外壁塗装','呼吸する漆喰で美しくメンテナンス性も。'],['05','屋根','耐久性の高い瓦屋根で美観と安心を両立。'],['06','シロアリ対策','防蟻処理と構造計画で長期にわたり安心。'],['07','免振','地震の揺れを吸収し家族を守る免震思想。'],['08','初期保証','長く安心をサポート。'],['09','内装ドア','デザイン性と機能性を兼ね備えた建具。'],['10','内壁・天井','自然素材で心地よい空間と空気を。'],['11','エコキュート','省エネ給湯で光熱費を抑える設備。'],['12','ACCS・エクリア','全館空調で快適な空気環境を実現。']
  ];
  return <main>
    <header className="header"><div className="header-inner"><a className="logo" href="#top">VIVANTE<span>by coconoie</span></a><nav className="nav"><a href="#concept">VIVANTEについて</a><a href="#product">商品コンセプト</a><a href="#spec">こだわり・性能</a><a href="#design">デザイン</a><a href="#movie">実例集</a><a href="#movie">YouTube</a><a href="#faq">よくあるご質問</a><a className="cta" href="#contact">✉ 資料請求・お問い合わせ</a></nav></div></header>
    <section id="top" className="hero"><div className="hero-copy"><p className="hero-brand">VIVANTE</p><h1 className="hero-title">100年、時を継ぐ家。</h1><p className="hero-lead">美しさと性能を両立し、<br/>100年後も愛され続ける住まいを。<br/>coconoieの新しい住まいのカタチ。</p><div className="btns"><a className="btn" href="#contact">▣ VIVANTEの資料を請求する →</a><a className="btn light" href="#contact">□ 無料相談を予約する →</a></div></div><div className="side-cta"><a href="#contact">資料請求</a><a href="#contact">見学予約</a><a href="#contact">無料相談</a></div></section>
    <section id="concept" className="section"><div className="container concept"><div><p className="eyebrow">CONCEPT</p><h2 className="h2">美しいだけでは、<br/>永く愛されない。</h2><p className="p">デザイン、性能、暮らしやすさ。そして建てた後の安心。それらすべてを調和した住まいだけが、時を超えて家族の暮らしを支え続けることができます。VIVANTEは、coconoieが考える新しいスタンダードです。</p><a className="btn outline" href="#spec" style={{marginTop:24}}>VIVANTEについて詳しく見る →</a></div><div className="concept-photos"><img className="main" src="/images/concept-main.jpg"/><div><img className="side" src="/images/concept-side1.jpg"/><img className="side" src="/images/concept-side2.jpg"/></div></div></div></section>
    <section className="features"><div className="container"><p className="eyebrow center">FEATURES</p><h2 className="feature-title">VIVANTEの4つの特徴</h2><div className="feature-grid"><div className="feature"><Icon type="house"/><h3>ヨーロッパの<br/>伝統美を感じる<br/>外観デザイン</h3><p className="small">本物の素材感とディテールにこだわった外観。</p></div><div className="feature"><Icon type="thermo"/><h3>高性能な<br/>快適性</h3><p className="small">断熱・気密・換気まで考え抜いた高性能住宅。</p></div><div className="feature"><Icon type="plan"/><h3>家事ラク動線と<br/>暮らしやすい間取り</h3><p className="small">毎日の暮らしがラクになる間取りをご提案。</p></div><div className="feature"><Icon type="heart"/><h3>建てた後も安心の<br/>アフター体制</h3><p className="small">100年後も安心して暮らせるサポート体制。</p></div></div></div></section>
    <section id="spec" className="spec"><div className="container"><h2 className="spec-title">VIVANTE STANDARD SPEC　標準仕様</h2><div className="spec-grid">{specs.map((s,i)=><div className="spec-card" key={s[0]}><img src={`/images/spec-${String(i+1).padStart(2,'0')}.jpg`}/><h3><span>{s[0]}</span>{s[1]}</h3><p>{s[2]}</p></div>)}</div><div className="spec-more"><a className="btn outline" href="#contact">すべての標準仕様を見る →</a></div></div></section>
    <section id="design" className="reason"><div className="reason-tabs"><div className="reason-title">100年住める理由が、<br/>ここにある。</div>{['高断熱','高気密','パッシブ設計','太陽光発電','レジリエンス','長寿命設計'].map((x,i)=><div className="reason-tab" key={x}><Icon type={i===0?'house':i===1?'sun':i===2?'leaf':i===3?'sun':i===4?'heart':'plan'}/>{x}</div>)}</div><div className="reason-gallery"><div className="reason-copy"><h2>時を重ねるほど、<br/>美しく。</h2><p>自然素材だからつくる、心地よい暮らしを。</p><a className="gold-btn" href="#contact">実例集を見る →</a></div><img src="/images/reason-1.jpg"/><img src="/images/reason-2.jpg"/><img src="/images/reason-3.jpg"/><img src="/images/reason-4.jpg"/></div></section>
    <section id="movie" className="media"><div className="container media-grid"><div><p className="eyebrow">MOVIE</p><h2>映像で体感するVIVANTE</h2><div className="movie-wrap"><img className="movie-img" src="/images/movie.jpg"/><span className="play">▶</span></div><a className="btn outline" href="#" style={{marginTop:18}}>YouTubeチャンネルを見る →</a></div><div><p className="eyebrow">INSTAGRAM</p><h2>施工事例や暮らしの風景</h2><div className="insta-grid"><img src="/images/insta1.jpg"/><img src="/images/insta2.jpg"/><img src="/images/insta3.jpg"/><img src="/images/insta4.jpg"/></div><a className="btn outline" href="#" style={{marginTop:18}}>Instagramを見る →</a></div><div className="brochure-box"><div><h2>まずは資料で知る</h2><p className="small">VIVANTEのコンセプトや仕様、実例をまとめたカタログを無料でお届けします。</p><a className="gold-btn" href="#contact">資料を請求する →</a></div><img src="/images/brochure.jpg"/></div></div></section>
    <section id="contact" className="contact"><div className="container contact-grid"><div><p className="eyebrow">CONTACT</p><h2>無料相談・お問い合わせ</h2><p>家づくりのこと、何でもお気軽にご相談ください。専門スタッフが丁寧にお応えします。</p><div className="contact-icons"><div className="contact-icon">費用相談</div><div className="contact-icon">いっしょに<br/>整理</div><div className="contact-icon">土地探し<br/>もOK</div></div></div><form className="form" onSubmit={submit}><div className="form-row"><input required className="input" name="name" value={form.name} onChange={update} placeholder="お名前　例）山田 太郎"/><input required className="input" name="phone" value={form.phone} onChange={update} placeholder="電話番号　例）090-1234-5678"/></div><div className="form-row"><input className="input" name="kana" value={form.kana} onChange={update} placeholder="ふりがな　例）やまだ たろう"/><input required type="email" className="input" name="email" value={form.email} onChange={update} placeholder="メールアドレス　例）example@mail.com"/></div><div className="form-row"><select className="select" name="landStatus" value={form.landStatus} onChange={update}><option value="">建築予定地を選択してください</option>{landOptions.map(v=><option key={v} value={v}>{v}</option>)}</select><select className="select" name="buildTiming" value={form.buildTiming} onChange={update}><option value="">ご予算目安を選択してください</option>{timingOptions.map(v=><option key={v} value={v}>{v}</option>)}</select></div><div><p className="label">ご相談内容</p><div className="checks">{requestOptions.map(v=><label key={v}><input type="checkbox" checked={form.requestType.includes(v)} onChange={()=>toggle(v)}/>{v}</label>)}</div></div><textarea className="textarea" name="message" value={form.message} onChange={update} placeholder="ご質問・ご要望など"/><button className="submit" disabled={status==='sending'}>{status==='sending'?'送信中...':'送信する →'}</button>{status==='success' && <p style={{color:'#9bd18f'}}>送信が完了しました。</p>}{status==='error' && <p style={{color:'#ffb4a8'}}>送信に失敗しました。</p>}</form></div></section>
    <footer className="footer">© coconoie All Rights Reserved.</footer>
  </main>
}
